// Example markdown content that can be used to test the markdown rendering
export const markdownTestContent = `# Data Analysis Results

Here's a comprehensive summary of your dataset:

## Key Fields
- **id**: Unique product identifier
- **name**: Product name  
- **brand**: Brand or manufacturer
- **category**: Product category (like Electronics, Apparel, Home & Living, Health & Beauty, etc.)
- **color, size**: Product attributes (with a wide variety of values and formats)
- **price**: Ranges from $1 to $999, with most products between $100 and $900
- **stock**: Quantity in stock (10 to 998 units)
- **availability**: Status such as \`in_stock\`, \`pre_order\`, \`backorder\`, \`limited_stock\`, \`out_of_stock\`, \`discontinued\`

## Key Insights

> There's a diverse mix of categories and brands.

- Most products are in stock or available for pre-order
- Some items are discontinued or out of stock and may need further review
- Color and size fields are varied and could benefit from standardization for clearer analysis
- No major missing values in key fields

## Business Recommendations

1. **Review and optimize inventory**, especially for discontinued or slow-moving items
2. **Standardize color and size attributes** for better analytics
3. **Regularly check product availability statuses** to keep your catalog accurate
4. **Consider pricing and promotional strategies** for both high- and low-priced products

## Sample Data

| Product | Price | Stock | Status |
|---------|-------|-------|--------|
| Widget A | $299 | 45 | in_stock |
| Widget B | $150 | 12 | limited_stock |
| Widget C | $899 | 0 | out_of_stock |

Your data is now ready for specific queries, visualizations, or deeper analysis. Let me know what you'd like to do next!

---

*This analysis was generated by the Data Analyst Agent.*`;

// Example of how to use the markdown content in a message
export const createMarkdownMessage = (content: string) => {
  return {
    id: Date.now().toString(),
    role: "assistant" as const,
    content: content,
    isStreaming: false,
  };
};
